apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: LoadBalancer
  selector:
    app: catalog  # Replace with the label selector for your deployment pods
  ports:
  - protocol: TCP
    port: 80  # External port exposed by the LoadBalancer
    targetPort: 8000  # Port your application listens on within the container

